version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: vfsystem
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
