version: '3'

services:
  app:
    build:
      context: .
    container_name: rest-api-sanctum
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - app-network