version: '3'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_KEY=base64:RFVf1RHhi38ZVV+I/yf4hhrhnQFbEDlkUXDxNeALiE8=
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-0-ap-northeast-1.pooler.supabase.com
      - DB_PORT=6543
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.aajfhlhsukhtzeqqzbds
      - DB_PASSWORD=5MLAmeWE_*qaJTm
    networks:
      - app-network
